# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ping unchama

on:
  push:
    branches:
      - master
      - main
    paths: 
      - "seichinetwork_jpmcs_about.html"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt install jq
      - name: Notify unchama
        env:
          GITHUB_HEAD: ${{github.head_ref}}
          GITHUB_BASE: ${{github.event.base_ref}}
          WEBHOOK_URL: ${{secrets.NOTIFY_WEBHOOK_URL}}
        run: |
          # https://discord.club
          jq -nc '{
            "username": "GiganticMinecraft/info-jpmcs.seichi.click",
            "avatar_url": "https://avatars.githubusercontent.com/u/31721007?v=4",
            "content": "<@233173508883087361>\nJMS説明文レポジトリに更新がプッシュされました。\nHTMLの差分を確認した上、minecraft.jpの説明文を更新してください。\n",
            "embeds": [],
            "components": [
              {
                "type": 1,
                "components": [
                  {
                    "type": 2,
                    "style": 5,
                    "label": "HTMLの差分",
                    "url": ("https://github.com/GiganticMinecraft/info-jpmcs.seichi.click/compare/" + env.GITHUB_HEAD + "..." + env.GITHUB_BASE)
                  }
                ]
              }
            ]
          }' | \
            curl -X POST -H "Content-Type: application/json" -d @- "$WEBHOOK_URL"
